-- This file is autogenerated by NIGHTFOX.
-- Do not make changes directly to this file.

local cmd = vim.fn.has("nvim") == 0 and vim.command or vim.cmd

if vim.g.colors_name then
  cmd("hi clear")
end

cmd("set termguicolors")
cmd("set background=dark")
vim.g.colors_name = "gruvfox"

cmd([[
highlight AerialGuide guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight Bold guifg=NONE guibg=NONE gui=bold guisp=NONE |
highlight BufferCurrent guifg=#ebdbb2 guibg=#bdae93 gui=NONE guisp=NONE |
highlight BufferCurrentIndex guifg=#458588 guibg=#bdae93 gui=NONE guisp=NONE |
highlight BufferCurrentMod guifg=#d79921 guibg=#bdae93 gui=NONE guisp=NONE |
highlight BufferCurrentSign guifg=#458588 guibg=#bdae93 gui=NONE guisp=NONE |
highlight BufferCurrentTarget guifg=#cc241d guibg=#bdae93 gui=NONE guisp=NONE |
highlight BufferInactive guifg=#817c9c guibg=#282828 gui=NONE guisp=NONE |
highlight BufferInactiveIndex guifg=#817c9c guibg=#282828 gui=NONE guisp=NONE |
highlight BufferInactiveMod guifg=#534733 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferInactiveSign guifg=#665c54 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferInactiveTarget guifg=#cc241d guibg=#282828 gui=NONE guisp=NONE |
highlight BufferTabpage guifg=#665c54 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferTabpages guifg=NONE guibg=#282828 gui=NONE guisp=NONE |
highlight BufferVisible guifg=#ebdbb2 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferVisibleIndex guifg=#458588 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferVisibleMod guifg=#d79921 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferVisibleSign guifg=#458588 guibg=#282828 gui=NONE guisp=NONE |
highlight BufferVisibleTarget guifg=#cc241d guibg=#282828 gui=NONE guisp=NONE |
highlight CmpDocumentation guifg=#ebdbb2 guibg=#282828 gui=NONE guisp=NONE |
highlight CmpDocumentationBorder guifg=#433c59 guibg=#282828 gui=NONE guisp=NONE |
highlight CmpItemAbbr guifg=#ebdbb2 guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemAbbrDeprecated guifg=#bdae93 guibg=NONE gui=strikethrough guisp=NONE |
highlight CmpItemAbbrMatch guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemAbbrMatchFuzzy guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemKindDefault guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight CmpItemKindSnippet guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight ColorColumn guifg=NONE guibg=#504945 gui=NONE guisp=NONE |
highlight Comment guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight Conceal guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight Conditional guifg=#ccb1ed guibg=NONE gui=NONE guisp=NONE |
highlight Constant guifg=#f0a4a2 guibg=NONE gui=NONE guisp=NONE |
highlight Cursor guifg=#3c3836 guibg=#ebdbb2 gui=NONE guisp=NONE |
highlight CursorLine guifg=NONE guibg=#665c54 gui=NONE guisp=NONE |
highlight CursorLineNr guifg=#d79921 guibg=NONE gui=bold guisp=NONE |
highlight DapUIBreakpointsCurrentLine guifg=#98971a guibg=NONE gui=bold guisp=NONE |
highlight DapUIBreakpointsDisabledLine guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight DapUIBreakpointsInfo guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIBreakpointsPath guifg=#a6dae3 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIDecoration guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIModifiedValue guifg=#ebdbb2 guibg=NONE gui=bold guisp=NONE |
highlight DapUIScope guifg=#a6dae3 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIStoppedThread guifg=#a6dae3 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIValue guifg=#ebdbb2 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIVariable guifg=#ebdbb2 guibg=NONE gui=NONE guisp=NONE |
highlight DapUIWatchesEmpty guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight DapUIWatchesError guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight DapUIWatchesValue guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight DashboardFooter guifg=#f0a4a2 guibg=NONE gui=italic guisp=NONE |
highlight DiagnosticError guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight DiagnosticHint guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight DiagnosticInfo guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight DiagnosticUnderlineError guifg=NONE guibg=NONE gui=undercurl guisp=#cc241d |
highlight DiagnosticUnderlineHint guifg=NONE guibg=NONE gui=undercurl guisp=#98971a |
highlight DiagnosticUnderlineInfo guifg=NONE guibg=NONE gui=undercurl guisp=#458588 |
highlight DiagnosticUnderlineWarn guifg=NONE guibg=NONE gui=undercurl guisp=#d79921 |
highlight DiagnosticVirtualTextError guifg=#cc241d guibg=#523532 gui=NONE guisp=NONE |
highlight DiagnosticVirtualTextHint guifg=#98971a guibg=#4a4632 gui=NONE guisp=NONE |
highlight DiagnosticVirtualTextInfo guifg=#458588 guibg=#3d4442 gui=NONE guisp=NONE |
highlight DiagnosticVirtualTextWarn guifg=#d79921 guibg=#534733 gui=NONE guisp=NONE |
highlight DiagnosticWarn guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight DiffAdd guifg=NONE guibg=#4e4b30 gui=NONE guisp=NONE |
highlight DiffChange guifg=NONE guibg=#3e4746 gui=NONE guisp=NONE |
highlight DiffDelete guifg=NONE guibg=#593431 gui=NONE guisp=NONE |
highlight DiffText guifg=NONE guibg=#405757 gui=NONE guisp=NONE |
highlight Directory guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight EndOfBuffer guifg=#3c3836 guibg=NONE gui=NONE guisp=NONE |
highlight Error guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight ErrorMsg guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight FernBranchText guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight FloatBorder guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight FoldColumn guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight Folded guifg=#bdae93 guibg=#504945 gui=NONE guisp=NONE |
highlight Function guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight GitGutterAdd guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight GitGutterChange guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight GitGutterDelete guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight GitSignsAdd guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight GitSignsChange guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight GitSignsDelete guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette0 guifg=#282828 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette1 guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette10 guifg=#b1d196 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette11 guifg=#f9cb8c guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette12 guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette13 guifg=#ccb1ed guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette14 guifg=#a6dae3 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette15 guifg=#e2e0f7 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette2 guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette3 guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette4 guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette5 guifg=#b16286 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette6 guifg=#689d6a guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette7 guifg=#e2e0f7 guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette8 guifg=#47407d guibg=NONE gui=NONE guisp=NONE |
highlight GlyphPalette9 guifg=#f083a2 guibg=NONE gui=NONE guisp=NONE |
highlight HopNextKey guifg=#689d6a guibg=NONE gui=bold guisp=NONE |
highlight HopNextKey1 guifg=#458588 guibg=NONE gui=bold guisp=NONE |
highlight HopNextKey2 guifg=#4a869c guibg=NONE gui=NONE guisp=NONE |
highlight HopUnmatched guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight Identifier guifg=#689d6a guibg=NONE gui=NONE guisp=NONE |
highlight IncSearch guifg=#433c59 guibg=#98971a gui=NONE guisp=NONE |
highlight Italic guifg=NONE guibg=NONE gui=italic guisp=NONE |
highlight Keyword guifg=#b16286 guibg=NONE gui=NONE guisp=NONE |
highlight LightspeedGreyWash guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight LineNr guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspCodeLens guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight LspCodeLensSeparator guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspFloatWinBorder guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspFloatWinNormal guifg=NONE guibg=#282828 gui=NONE guisp=NONE |
highlight LspReferenceRead guifg=NONE guibg=#433c59 gui=NONE guisp=NONE |
highlight LspReferenceText guifg=NONE guibg=#433c59 gui=NONE guisp=NONE |
highlight LspReferenceWrite guifg=NONE guibg=#433c59 gui=NONE guisp=NONE |
highlight LspSagaCodeActionBorder guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaDefPreviewBorder guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaFinderSelection guifg=#433c59 guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaHoverBorder guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaRenameBorder guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight LspSagaSignatureHelpBorder guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight LspSignatureActiveParameter guifg=#63577d guibg=NONE gui=NONE guisp=NONE |
highlight LspTroubleCount guifg=#b16286 guibg=#bdae93 gui=NONE guisp=NONE |
highlight LspTroubleNormal guifg=#bdae93 guibg=#282828 gui=NONE guisp=NONE |
highlight LspTroubleText guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight MatchParen guifg=#d79921 guibg=NONE gui=bold guisp=NONE |
highlight ModeMsg guifg=#d79921 guibg=NONE gui=bold guisp=NONE |
highlight ModesCopy guifg=NONE guibg=#d79921 gui=NONE guisp=NONE |
highlight ModesDelete guifg=NONE guibg=#cc241d gui=NONE guisp=NONE |
highlight ModesInsert guifg=NONE guibg=#689d6a gui=NONE guisp=NONE |
highlight ModesVisual guifg=NONE guibg=#b16286 gui=NONE guisp=NONE |
highlight MoreMsg guifg=#458588 guibg=NONE gui=bold guisp=NONE |
highlight NeoTreeDirectoryIcon guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeDirectoryName guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeDotfile guifg=#4a869c guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeFileName guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeFileNameOpened guifg=#ebdbb2 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitAdded guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitConflict guifg=#d65d0e guibg=NONE gui=italic guisp=NONE |
highlight NeoTreeGitDeleted guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitIgnored guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitModified guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeGitUntracked guifg=#a580d2 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeIndentMarker guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight NeoTreeNormal guifg=#ebdbb2 guibg=#282828 gui=NONE guisp=NONE |
highlight NeoTreeRootName guifg=#d65d0e guibg=NONE gui=bold guisp=NONE |
highlight NeoTreeSymbolicLinkTarget guifg=#d871a6 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitBranch guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitDiffAdd guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight NeogitDiffAddHighlight guifg=NONE guibg=#4e4b30 gui=NONE guisp=NONE |
highlight NeogitDiffContextHighlight guifg=NONE guibg=#3e4746 gui=NONE guisp=NONE |
highlight NeogitDiffDelete guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight NeogitDiffDeleteHighlight guifg=NONE guibg=#593431 gui=NONE guisp=NONE |
highlight NeogitHunkHeader guifg=#458588 guibg=#665c54 gui=NONE guisp=NONE |
highlight NeogitHunkHeaderHighlight guifg=#458588 guibg=#433c59 gui=NONE guisp=NONE |
highlight NeogitNotificationError guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight NeogitNotificationInfo guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitNotificationWarning guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight NeogitRemote guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight NonText guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight Normal guifg=#ebdbb2 guibg=#3c3836 gui=NONE guisp=NONE |
highlight NormalFloat guifg=#ebdbb2 guibg=#282828 gui=NONE guisp=NONE |
highlight NormalNC guifg=#ebdbb2 guibg=#3c3836 gui=NONE guisp=NONE |
highlight NotifyDEBUGBorder guifg=#6a6828 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyDEBUGTitle guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight NotifyERRORBorder guifg=#842e2a guibg=NONE gui=NONE guisp=NONE |
highlight NotifyERRORTitle guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight NotifyINFOBorder guifg=#405e5f guibg=NONE gui=NONE guisp=NONE |
highlight NotifyINFOTitle guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyTRACEBorder guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight NotifyTRACETitle guifg=#817c9c guibg=NONE gui=NONE guisp=NONE |
highlight NotifyWARNBorder guifg=#8a682c guibg=NONE gui=NONE guisp=NONE |
highlight NotifyWARNTitle guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight Number guifg=#d65d0e guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeEmptyFolderName guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeFolderIcon guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeFolderName guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitDeleted guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitDirty guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitMerge guifg=#d65d0e guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeGitNew guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeImageFile guifg=#b1acde guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeIndentMarker guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeNormal guifg=#ebdbb2 guibg=#282828 gui=NONE guisp=NONE |
highlight NvimTreeOpenedFile guifg=#f0a6cc guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeOpenedFolderName guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeRootFolder guifg=#d65d0e guibg=NONE gui=bold guisp=NONE |
highlight NvimTreeSpecialFile guifg=#689d6a guibg=NONE gui=NONE guisp=NONE |
highlight NvimTreeSymlink guifg=#d871a6 guibg=NONE gui=NONE guisp=NONE |
highlight Operator guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight Pmenu guifg=#ebdbb2 guibg=#433c59 gui=NONE guisp=NONE |
highlight PmenuSel guifg=NONE guibg=#63577d gui=NONE guisp=NONE |
highlight PmenuThumb guifg=NONE guibg=#63577d gui=NONE guisp=NONE |
highlight PounceAccept guifg=#3c3836 guibg=#f0a4a2 gui=NONE guisp=NONE |
highlight PounceAcceptBest guifg=#3c3836 guibg=#a6dae3 gui=NONE guisp=NONE |
highlight PounceGap guifg=#ebdbb2 guibg=#433c59 gui=NONE guisp=NONE |
highlight PounceMatch guifg=#ebdbb2 guibg=#63577d gui=NONE guisp=NONE |
highlight PreProc guifg=#f0a6cc guibg=NONE gui=NONE guisp=NONE |
highlight Search guifg=#ebdbb2 guibg=#63577d gui=NONE guisp=NONE |
highlight SignColumn guifg=#bdae93 guibg=NONE gui=NONE guisp=NONE |
highlight Sneak guifg=#282828 guibg=#b16286 gui=NONE guisp=NONE |
highlight SneakScope guifg=NONE guibg=#433c59 gui=NONE guisp=NONE |
highlight Special guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight SpellBad guifg=NONE guibg=NONE gui=undercurl guisp=#cc241d |
highlight SpellCap guifg=NONE guibg=NONE gui=undercurl guisp=#d79921 |
highlight SpellLocal guifg=NONE guibg=NONE gui=undercurl guisp=#458588 |
highlight SpellRare guifg=NONE guibg=NONE gui=undercurl guisp=#458588 |
highlight Statement guifg=#b16286 guibg=NONE gui=NONE guisp=NONE |
highlight StatusLine guifg=#d5c4a1 guibg=#282828 gui=NONE guisp=NONE |
highlight StatusLineNC guifg=#bdae93 guibg=#282828 gui=NONE guisp=NONE |
highlight String guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight Substitute guifg=#3c3836 guibg=#cc241d gui=NONE guisp=NONE |
highlight TSConstBuiltin guifg=#f0a4a2 guibg=NONE gui=NONE guisp=NONE |
highlight TSConstructor guifg=#b16286 guibg=NONE gui=NONE guisp=NONE |
highlight TSDanger guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight TSError guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight TSField guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight TSFuncBuiltin guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight TSFuncMacro guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight TSKeywordFunction guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight TSKeywordOperator guifg=#d5c4a1 guibg=NONE gui=bold guisp=NONE |
highlight TSNamespace guifg=#a6dae3 guibg=NONE gui=NONE guisp=NONE |
highlight TSNote guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight TSOperator guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight TSPunctBracket guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight TSPunctDelimiter guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight TSPunctSpecial guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight TSStringEscape guifg=#f9cb8c guibg=NONE gui=bold guisp=NONE |
highlight TSStringRegex guifg=#f9cb8c guibg=NONE gui=NONE guisp=NONE |
highlight TSTextReference guifg=#b16286 guibg=NONE gui=NONE guisp=NONE |
highlight TSTypeBuiltin guifg=#a6dae3 guibg=NONE gui=NONE guisp=NONE |
highlight TSURI guifg=#689d6a guibg=NONE gui=bold guisp=NONE |
highlight TSVariable guifg=#ebdbb2 guibg=NONE gui=NONE guisp=NONE |
highlight TSVariableBuiltin guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight TSWarning guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight TabLine guifg=#bdae93 guibg=#504945 gui=NONE guisp=NONE |
highlight TabLineFill guifg=NONE guibg=#282828 gui=NONE guisp=NONE |
highlight TabLineSel guifg=#d5c4a1 guibg=#7c6f64 gui=NONE guisp=NONE |
highlight TelescopeBorder guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight TelescopeSelectionCaret guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight Title guifg=#65b1cd guibg=NONE gui=NONE guisp=NONE |
highlight Todo guifg=#3c3836 guibg=#458588 gui=NONE guisp=NONE |
highlight Type guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight Underlined guifg=NONE guibg=NONE gui=underline guisp=NONE |
highlight VertSplit guifg=#7c6f64 guibg=NONE gui=NONE guisp=NONE |
highlight Visual guifg=NONE guibg=#433c59 gui=NONE guisp=NONE |
highlight WarningMsg guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight WhichKeyFloat guifg=NONE guibg=#282828 gui=NONE guisp=NONE |
highlight Whitespace guifg=#504945 guibg=NONE gui=NONE guisp=NONE |
highlight diffAdded guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight diffChanged guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight diffFile guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight diffIndexLine guifg=#f0a6cc guibg=NONE gui=NONE guisp=NONE |
highlight diffLine guifg=#f0a4a2 guibg=NONE gui=NONE guisp=NONE |
highlight diffNewFile guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight diffOldFile guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight diffRemoved guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol1 guifg=#cc241d guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol2 guifg=#d79921 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol3 guifg=#98971a guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol4 guifg=#458588 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol5 guifg=#689d6a guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol6 guifg=#b16286 guibg=NONE gui=NONE guisp=NONE |
highlight rainbowcol7 guifg=#eb98c3 guibg=NONE gui=NONE guisp=NONE |
highlight rustTSField guifg=#d5c4a1 guibg=NONE gui=NONE guisp=NONE |
highlight! link AerialLine Search |
highlight! link Boolean Number |
highlight! link Character String |
highlight! link CmpItemKindClass Type |
highlight! link CmpItemKindConstant TSConstant |
highlight! link CmpItemKindConstructor Function |
highlight! link CmpItemKindEnum Constant |
highlight! link CmpItemKindEnumMember TSField |
highlight! link CmpItemKindEvent Constant |
highlight! link CmpItemKindField TSField |
highlight! link CmpItemKindFunction Function |
highlight! link CmpItemKindInterface Constant |
highlight! link CmpItemKindKeyword Identifier |
highlight! link CmpItemKindMethod Function |
highlight! link CmpItemKindModule TSNamespace |
highlight! link CmpItemKindOperator Operator |
highlight! link CmpItemKindProperty TSProperty |
highlight! link CmpItemKindReference Keyword |
highlight! link CmpItemKindStruct Type |
highlight! link CmpItemKindTypeParameter TSField |
highlight! link CmpItemKindUnit Constant |
highlight! link CmpItemKindValue Keyword |
highlight! link CmpItemKindVariable TSVariable |
highlight! link CmpItemMenu Comment |
highlight! link CurSearch IncSearch |
highlight! link CursorColumn CursorLine |
highlight! link CursorIM Cursor |
highlight! link DapUIBreakpointsLine DapUILineNumber |
highlight! link DapUIFloatBorder FloatBorder |
highlight! link DapUIFrameName Normal |
highlight! link DapUILineNumber Number |
highlight! link DapUISource Keyword |
highlight! link DapUIThread String |
highlight! link DapUIType Type |
highlight! link DashboardCenter String |
highlight! link DashboardHeader Title |
highlight! link DashboardShortCut Identifier |
highlight! link Debug Special |
highlight! link Define PreProc |
highlight! link Delimiter Special |
highlight! link DiagnosticSignError DiagnosticError |
highlight! link DiagnosticSignHint DiagnosticHint |
highlight! link DiagnosticSignInfo DiagnosticInfo |
highlight! link DiagnosticSignWarn DiagnosticWarn |
highlight! link Exception Keyword |
highlight! link FidgetTask LineNr |
highlight! link FidgetTitle Title |
highlight! link Float Number |
highlight! link FocusedSymbol Search |
highlight! link Include PreProc |
highlight! link Label Conditional |
highlight! link LspSagaBorderTitle Title |
highlight! link LspSagaCodeActionContent String |
highlight! link LspSagaCodeActionTitle Title |
highlight! link Macro PreProc |
highlight! link NeoTreeDimText Conceal |
highlight! link NeoTreeNormalNC NeoTreeNormal |
highlight! link NotifyDEBUGIcon NotifyDEBUGTitle |
highlight! link NotifyERRORIcon NotifyERRORTitle |
highlight! link NotifyINFOIcon NotifyINFOTitle |
highlight! link NotifyTRACEIcon NotifyTRACETitle |
highlight! link NotifyWARNIcon NotifyWARNTitle |
highlight! link NvimTreeGitRenamed NvimTreeGitDeleted |
highlight! link NvimTreeGitStaged NvimTreeGitStaged |
highlight! link NvimTreeVertSplit VertSplit |
highlight! link PmenuSbar Pmenu |
highlight! link PreCondit PreProc |
highlight! link Question MoreMsg |
highlight! link QuickFixLine CursorLine |
highlight! link Repeat Conditional |
highlight! link SignColumnSB SignColumn |
highlight! link SpecialChar Special |
highlight! link SpecialComment Special |
highlight! link SpecialKey NonText |
highlight! link StorageClass Type |
highlight! link Structure Type |
highlight! link SymbolOutlineConnector Conceal |
highlight! link TSAttribute Constant |
highlight! link TSProperty TSField |
highlight! link Tag Special |
highlight! link TelescopeMatching Search |
highlight! link TelescopeSelection CursorLine |
highlight! link Typedef Type |
highlight! link VisualNOS visual |
highlight! link WhichKey Identifier |
highlight! link WhichKeyDesc Keyword |
highlight! link WhichKeyGroup Function |
highlight! link WhichKeySeparator Comment |
highlight! link WhichKeySeperator Comment |
highlight! link WhichKeyValue Comment |
highlight! link WildMenu Pmenu |
highlight! link illuminatedCurWord LspReferenceText |
highlight! link illuminatedWord LspReferenceText |
highlight! link lCursor Cursor |
highlight! link qfFileName Directory |
highlight! link qfLineNr lineNr
]])

local function set_terminal()
   -- stylua: ignore
  local colors = {
    "#282828", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#ebdbb2", "#47407d", "#f083a2", "#b1d196", "#f9cb8c", "#65b1cd", "#ccb1ed", "#a6dae3", "#e2e0f7",
  }
  for i, c in ipairs(colors) do
    local n = "terminal_color_" .. i - 1
    vim.g[n] = c
  end
  if vim.fn.has("nvim") == 0 then
    vim.g.terminal_ansi_colors = vim.list(colors)
  end
end

set_terminal()
